version: '2'

services:
  dashboard_db:
    image: postgres
    env_file: ./environment
    ports:
    - "5434:5432"

  advertima_web:
    build: .
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    depends_on:
      - dashboard_db
    env_file: ./environment
    environment:
      - PORT=9000
