version: '2'

services:
  dashboard_db:
    image: postgres
    env_file: ./environment
    expose:
      - "5434"
    ports:
      - "5434:5432"

  advertima_web:
    build: .
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    links:
      - dashboard_db
    depends_on:
      - dashboard_db
    env_file: ./environment
    environment:
      - PORT=9000
